hardening, fix bugs

diff --git a/src/bin/print-progress b/src/bin/print-progress
--- a/src/bin/print-progress
+++ b/src/bin/print-progress
@@ -1,4 +1,10 @@
-#!/bin/bash
+#!/usr/bin/env bash
+#
+# Description: prints a progress bar to standard output.
+# Usage: print-progress [options]
+#
+
+set -euo pipefail
 
 width=${PROGRESS_BAR_WIDTH:-50}
 done_char=${PROGRESS_BAR_DONE_CHAR:-"#"}
@@ -8,50 +14,62 @@ open_bracket=${PROGRESS_BAR_OPEN_BRACKET:-"["}
 close_bracket=${PROGRESS_BAR_CLOSE_BRACKET:-"]"}
 
 usage() {
-	echo "Usage: $(basename "$0") [-h] [-w width] [-d done_char] [-l left_char] [-p prefix] [-o open_bracket] [-c close_bracket] currentState totalState [task_description]"
+  echo "Usage: $(basename "$0") [-h] [-w width] [-d done_char] [-l left_char] [-p prefix] [-o open_bracket] [-c close_bracket] currentState totalState [task_description]"
 }
 while getopts "hw:d:l:p:o:c:" arg; do
-	case $arg in
-	h)
-		usage
-		exit 0
-		;;
-	w)
-		width="$OPTARG"
-		;;
-	d)
-		done_char="$OPTARG"
-		;;
-	l)
-		left_char="$OPTARG"
-		;;
-	p)
-		prefix="$OPTARG"
-		;;
-	o)
-		open_bracket="$OPTARG"
-		;;
-	c)
-		close_bracket="$OPTARG"
-		;;
-	*)
-		usage
-		exit 1
-		;;
-	esac
+  case $arg in
+  h)
+    usage
+    exit 0
+    ;;
+  w)
+    width="$OPTARG"
+    ;;
+  d)
+    done_char="$OPTARG"
+    ;;
+  l)
+    left_char="$OPTARG"
+    ;;
+  p)
+    prefix="$OPTARG"
+    ;;
+  o)
+    open_bracket="$OPTARG"
+    ;;
+  c)
+    close_bracket="$OPTARG"
+    ;;
+  *)
+    usage
+    exit 1
+    ;;
+  esac
 done
 shift $((OPTIND - 1))
 if [[ $# -ne 2 ]] && [[ $# -ne 3 ]]; then
-	usage
-	exit 0
+  usage
+  exit 1
 fi
 
 readonly currentState=$1
 readonly totalState=$2
+
+# Validate integers
+if ! [[ "$currentState" =~ ^[0-9]+$ ]] || ! [[ "$totalState" =~ ^[0-9]+$ ]]; then
+  echo "Error: currentState and totalState must be non-negative integers" >&2
+  exit 1
+fi
+
+if [[ "$totalState" -eq 0 ]]; then
+  echo "Error: totalState cannot be zero" >&2
+  exit 1
+fi
+
 if [[ $# -eq 3 ]]; then
-	readonly task_description=" $3"
+  readonly task_description=" $3"
 else
-	readonly task_description=""
+  readonly task_description=""
 fi
 
 readonly percentage=$((currentState * 100 / totalState))
@@ -60,13 +78,15 @@ readonly done_length=$(((percentage * width) / 100))
 readonly left_length=$((width - done_length))
 
 done_string=$(printf "%${done_length}s")
-left_string=$(printf "%${left_length}s")
+done_string=${done_string// /$done_char}
+readonly done_string
 
-readonly done_string=${done_string// /$done_char}
-readonly left_string=${left_string// /$left_char}
+left_string=$(printf "%${left_length}s")
+left_string=${left_string// /$left_char}
+readonly left_string
 
 printf "\r%s%s%s%s%s%4d%%%s" \
-	"$prefix" \
-	"$open_bracket" "$done_string" "$left_string" "$close_bracket" \
-	"$percentage" \
-	"$task_description"
+  "$prefix" \
+  "$open_bracket" "$done_string" "$left_string" "$close_bracket" \
+  "$percentage" \
+  "$task_description"
